# Generated by Django 3.0.4 on 2020-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
