# Generated by Django 3.0.4 on 2020-06-13 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200613_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyjob',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapyjob',
            name='task',
            field=models.CharField(default='-', max_length=25),
        ),
    ]
