# Generated by Django 3.0.4 on 2020-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200613_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ascensor',
            new_name='elevator',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='superficie',
            new_name='surface',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='tipo',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='scrapyjob',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
