# Generated by Django 3.0.4 on 2020-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200317_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
