# Generated by Django 3.0.4 on 2020-08-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_property_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='property',
            new_name='prop',
        ),
        migrations.RemoveField(
            model_name='property',
            name='posts_found',
        ),
    ]
