# Generated by Django 3.0.4 on 2020-03-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200317_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
