# Generated by Django 3.0.4 on 2020-08-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200810_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
